[package]
name = "dibz"
version = "0.1.0"
authors = ["limisi"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.8"
pickledb = "0.4.1"
dirs = "3.0.1"
